config/routes.rb
Rails.application.routes.draw do
  resources :floors
  resources :departments
  devise_for :users
  resources :employees
  root 'home#index'

  get "export_contacts", to: "employees#export"
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
  has_one_attached :photo
  has_many :subordinates, class_name: "Employee", foreign_key: "manager_id"
  belongs_to :manager, class_name: "Employee", optional: true
  after_commit :default_photo, on: %i[create update]

  def self.todays_birthdays
    coming_up(:date_of_birth)
  end

  def self.upcoming_birthdays
    coming_up(:date_of_birth, days: 14)
  end

  def photo_thumbnail
    photo = self.photo
    if photo.attached?
      photo.variant(resize: "90x90!").processed
    else
      "avatar.jpg"
    end
  end

  def photo_thumbnail_upcoming_birthdays
    photo = self.photo
    if photo.attached?
      photo.variant(resize: "50x50!").processed
    else
      "avatar.jpg"
    end
  end

  def manager_photo
    manager = self.manager
    if manager.present? && manager.photo.attached?
      manager.photo.variant(resize: '90x90!').processed
    else
      "avatar.jpg"
    end
  end

  enum roles: {
    employee: 0,
    coordinator: 1,
    supervisor: 2,
    manager: 3
  }

  paginates_per 3

  private

  def default_photo
    unless self.photo.attached?
      self.photo.attach(
        io: File.open(
          Rails.root.join(
            'app', 'assets', 'images', 'avatar.jpg'
          )
        ),
        filename: 'avatar.jpg',
        content_type: 'image/jpg'
      )
    end
  end

  def self.coming_up(date_field, days: 0)
    date_in_current_year = <<~SQL
      make_date(
        EXTRACT(YEAR FROM CURRENT_DATE) :: int,
        EXTRACT(MONTH FROM #{date_field}) :: int,
        EXTRACT(DAY FROM #{date_field}) :: int
      )
    SQL

    ::Employee
      .where(id: Employee.ids)
      .select(:id)
      .select("#{date_in_current_year} AS #{date_field}")
      .select(:first_name)
      .select(:last_name)
      .select(:title)
      .select("(EXTRACT(YEAR from CURRENT_DATE) - EXTRACT(YEAR from #{date_field})) :: int AS will_be")
      .where("#{date_in_current_year} BETWEEN CURRENT_DATE AND (CURRENT_DATE + '#{days} days' :: interval)")
      .where("(EXTRACT(YEAR from CURRENT_DATE) - EXTRACT(YEAR from #{date_field})) :: int BETWEEN 1 AND 150")
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :export]
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @q = Employee.ransack(params[:q])
    @employees = @q.result.page(params[:page]).per(10)
  end

  def export
    @employees = Employee.all

    respond_to do |format|
      format.pdf do
        render pdf: "Contacts: #{@employees.count}",
        page_size: 'A4',
        layout: "exports/contacts_layout.pdf.erb",
        template: "exports/contacts.html.erb",
        orientation: "landscape",
        lowquality: true,
        dpi: 96
      end
    end
  end

  # GET /employees/1 or /employees/1.json
  def show
    @coworkers = @employee.department.employees.where.not(id: @employee.id)
                          .order(:first_name).page(params[:page])
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
         format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created!" }
         format.json { render :show, status: :created, location: @employee }
      else
         format.html { render :new, status: :unprocessable_entity }
         format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated!" }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(
        :roles, :photo, :first_name,
        :last_name, :company, :title,
        :email, :phone, :department_id,
        :date_of_birth, :manager_id
      )
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def tel_to(text)
    groups = text.to_s.scan(/(?:^\+)?\d+/)
    link_to text, "tel:#{groups.join '-'}"
  end
end

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col sm-8 mb-3">
    <div class="actions">
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= form.submit class:"btn btn-success text-white me-md-2" %>
        <%= link_to 'Go Back', employees_path, class:"btn btn-outline-primary text-primary" %>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <div class="mb-3">
        <%= image_tag employee.photo_thumbnail,
          size:"90",
          class:"img-circle img-bordered-sm"
        %>
      </div>

      <div class="row mb-3">
        <div class="col-sm-4">
          <%= form.label :photo, for:"formFile", class:"form-label", placeholder:"Profile Photo" %>
          <%= form.file_field :photo, class:"form-control", id:"formFile" %>
        </div>

        <div class="col-sm-2">
          <%= form.label :Role %>
          <%= form.collection_select :roles, Employee.roles.map{ |role| [role.first, role.first.capitalize] }, :first, :second, { include_blank: true }, {class: "custom-select rounded-0"} %>
        </div>

        <div class="col-sm-4">
          <%= form.label :Manager %>
          <%= form.select :manager_id, Employee.manager.collect{ |m| [m.first_name + ' ' + m.last_name, m.id] }, { include_blank: true }, {class: "custom-select rounded-0"} %>
        </div>

        <div class="col-sm-2">
          <%= form.label :Department %>
          <%= form.select :department_id, options_for_select(Department.order(:description).pluck(:description, :id)), {}, {class: "custom-select rounded-0"} %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-2">
          <%= form.label :date_of_birth %>
          <%= form.date_field :date_of_birth, class:"form-control datetimepicker-input", "data-target":"#dateOfBirth" %>
        </div>

        <div class="col-sm-4">
          <%= form.label :first_name, for:"floatingInputFirsName" %>
          <%= form.text_field :first_name, class:"form-control", id:"floatingInputFirsName", placeholder:"John" %>
        </div>

        <div class="col-sm-6">
          <%= form.label :last_name, for:"floatingInputLastName" %>
          <%= form.text_field :last_name, class:"form-control", id:"floatingInputLastName", placeholder:"Doe" %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-6">
          <%= form.label :company, for:"floatingInputCompany" %>
          <%= form.text_field :company, class:"form-control", id:"floatingInputCompany", placeholder:"Marvel" %>
        </div>

        <div class="col-sm-6">
          <%= form.label :title, for:"floatingInputTitle" %>
          <%= form.text_field :title, class:"form-control", id:"floatingInputTitle", placeholder:"Ruby on Rails Developer" %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-sm-6">
          <%= form.label :email, for:"floatingInputEmail" %>
          <%= form.text_field :email, class:"form-control", id:"floatingInputEmail", placeholder:"johndoe@email.com" %>
        </div>

        <div class="col-sm-6">
          <%= form.label :phone, for:"floatingInputPhone" %>
          <%= form.text_field :phone, class:"form-control", id:"floatingInputPhone", placeholder:"00000-0000" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="row mb-3">
  <div class="col sm-8">
    <h1>Editing Employee</h1>
  </div>
</div>
<%= render 'form', employee: @employee %>

app/views/employees/index.html.erb
<div class="container-fluid">
  <div class="row mb-3 mt-3">
    <% if user_signed_in? %>
      <div class="col-sm-12">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <%= link_to 'New Employee', new_employee_path, class:"btn btn-primary text-white me-md-2 rounded-pill border border-light" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Employees</h3>
          <div class="col-sm-12 col-md-6">
            <div class="dt-buttons btn-group flex-wrap">
              <%= link_to export_contacts_path(format: 'pdf'), class:"btn btn-tool btn-sm", "data-bs-toggle":"tooltip", "data-bs-placement":"top", title:"Export" do =%>
                <i class="fas fa-download"></i>
              <% end %>
              </a>
            </div>
          </div>
          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 250px;">
              <%= search_form_for @q do |f| %>
                <div class="input-group-append">
                  <%= f.label 'Search:', class:"mr-2"%>
                  <%= f.search_field :first_name_cont, class: "form-control form-control-sm float-right", placeholder: "John Doe" %>
                  <% f.submit class: "btn btn-default" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>Name</th>
                <th>Title</th>
                <th>Date of Birth</th>
                <th>Company</th>
                <th>Department</th>
                <th>Floor</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @employees.each do |employee| %>
                <tr>
                  <td><%= employee.first_name %> <%= employee.last_name %></td>
                  <td><%= employee.title %></td>
                  <td><%= employee.date_of_birth %></td>
                  <td><%= employee.company %></td>
                  <td><%= employee.department.description %></td>
                  <td><%= employee.department.floor.description %></td>
                  <td>
                    <%= link_to employee,
                      class:"btn btn-sm btn-primary",
                      style:"margin-bottom: 5px;",
                      "data-bs-toggle":"tooltip",
                      "data-bs-placement":"top",
                      title:"View" do %>
                        <i class="fas fa-user"></i>
                      <% end %>
                    <% if user_signed_in? %>
                      <%= link_to edit_employee_path(employee),
                        class:"btn btn-sm btn-info",
                        style:"margin-bottom: 5px;",
                        "data-bs-toggle":"tooltip",
                        "data-bs-placement":"top",
                        title:"Edit" do %>
                          <i class="fas fa-pen"></i>
                        <% end %>
                      <%= link_to employee,
                        method: :delete, data: { confirm: 'Are you sure?' },
                        class:"btn btn-sm btn-danger",
                        style:"margin-bottom: 5px;",
                        "data-bs-toggle":"tooltip",
                        "data-bs-placement":"top",
                        title:"Delete" do %>
                          <i class="fas fa-trash-alt"></i>
                        <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12 col-md-7">
          <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
            <%= paginate @employees %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="row mb-3">
  <div class="col sm-8">
    <h1>New Employee</h1>
  </div>
</div>
<%= render 'form', employee: @employee %>

app/views/employees/show.html.erb
<div class="row justify-content-end">
  <div class="col-xl-2 col-lg-2 col-md-2 mb-3 align-self-end">
    <div class="btn-group-vertical d-grid gap-2 d-flex justify-content-end">
      <% if user_signed_in? %>
        <%= link_to 'Edit', edit_employee_path(@employee),class:"btn btn-success text-white" %>
      <% end %>
        <%= link_to 'Go Back', employees_path, class:"btn btn-outline-dark" %>
    </div>
  </div>
</div>

<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
        <div class="card card-lightblue card-outline">
          <div class="card-body box-profile">
            <div class="text-center">
                <%= image_tag @employee.photo_thumbnail,
                    class:"profile-user-img img-fluid img-circle"
                %>
            </div>

            <h3 class="profile-username text-center"><%= @employee.first_name %> <%= @employee.last_name %></h3>

            <p class="text-muted text-center"><%= @employee.company %></p>

            <ul class="list-group list-group-unbordered mb-3">
              <li class="list-group-item">
                <b>Phone</b> <a class="float-right" style="text-decoration: none !important" > <%= @employee.phone %></a>
              </li>
              <li class="list-group-item">
                <b>Email</b> <a class="float-right" style="text-decoration: none !important" > <%= @employee.email %></a>
              </li>
              <li class="list-group-item">
                <b>Title</b> <a class="float-right" style="text-decoration: none !important" ><%= @employee.title %></a>
              </li>
              <li class="list-group-item">
                <b>Date of Birth</b> <a class="float-right" style="text-decoration: none !important" ><%= @employee.date_of_birth %></a>
              </li>
            </ul>

            <%= mail_to @employee.email, class:"btn btn-success btn-block" , style:"margin-bottom: 5px;", "data-bs-toggle":"tooltip", "data-bs-placement":"top", title:"Delete"  do %>
              <i class="fas fa-envelope mr-1"></i>Contact User
            <% end %>
          </div>
        </div>

        <div class="card card-lightblue">
          <div class="card-header">
            <h3 class="card-title">About Me</h3>
          </div>
          <div class="card-body">
            <strong><i class="fas fa-bullseye mr-1"></i></i>Department</strong>
            <p class="text-muted">
              <%= @employee.department.description %>
            </p>
            <hr>
            <strong><i class="fas fa-map-marker-alt mr-1"></i>Floor</strong>
            <p class="text-muted">
              <%= @employee.department.floor.description %>
            </p>
          </div>
        </div>
      </div>

      <div class="col-md-9">
        <div class="card">
          <div class="card-body">
            <div class="tab-content">
              <div class="active tab-pane" id="manager">
                <div class="post">
                  <div class="user-block">
                      <%= image_tag @employee.manager_photo,
                        class:"img-circle img-bordered-sm"
                      %>
                    <span class="username">
                      <% if @employee.manager.nil? %>
                        <a>Employee does not have a manager!</a>
                      <% else %>
                        <%= link_to @employee.manager do %>
                          <%= @employee.manager.first_name %>
                          <%= @employee.manager.last_name %>
                        <% end %>
                      </span>
                    <% end %>
                    <% unless @employee.manager.nil? %>
                      <span class="description"><%= @employee.manager.roles.capitalize %></span>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="card card-solid">
          <div class="card-header border-0">
            <h3 class="card-title">Coworkers</h3>
            </div>
            <div class="card-body pb-0">
              <div class="row">
                <% @coworkers.each do |coworker| %>
                  <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch flex-column">
                    <div class="card bg-light d-flex flex-fill">
                      <div class="card-header text-muted border-bottom-0">
                      </div>
                      <div class="card-body pt-0">
                        <div class="row">
                          <div class="col-7">
                            <h2 class="lead"><b><%= coworker.first_name %> <%= coworker.last_name %></b></h2>
                            <p class="text-muted text-sm"><b>About: </b> <%= coworker.roles.capitalize %></p>
                            <ul class="ml-4 mb-0 fa-ul text-muted">
                              <li class="small mb-2"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> <%= coworker.company %></li>
                              <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> <%= coworker.phone %></li>
                            </ul>
                          </div>
                          <div class="col-5 text-center">
                            <% if coworker.photo.attached? %>
                              <%= image_tag coworker.photo.variant(resize_to_limit: [70, 70]).processed,
                                  width: 70,
                                  heigth: 70,
                                  class:"img-circle img-bordered-sm"
                              %>
                            <% else %>
                              <%= image_tag ("avatar.jpg"), size:"70", class:"img-circle img-bordered-sm" %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                      <div class="card-footer">
                        <div class="text-right">
                          <%= link_to employee_path(coworker.id), class:"btn btn-sm btn-success" do %>
                            <i class="fas fa-user"></i>
                              View Profile
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="card-footer">
              <nav aria-label="Contacts Page Navigation">
                <ul class="pagination justify-content-center m-0">
                  <%= paginate @coworkers %>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>