config/routes.rb
Rails.application.routes.draw do
  resources :floors
  resources :departments
  devise_for :users
  resources :employees
  root 'home#index'

  get "export_contacts", to: "employees#export"
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees
  belongs_to :floor
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to department_url(@department), notice: "Department was successfully created!" }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to department_url(@department), notice: "Department was successfully updated!" }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Department was successfully destroyed!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:description, :floor_id)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_with(model: department) do |form| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col sm-8 mb-3">
    <div class="actions">
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= form.submit class:"btn btn-success text-white me-md-2" %>
        <%= link_to 'Go Back', departments_path, class:"btn btn-outline-primary text-primary" %>
      </div>
    </div>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :description, class:"form-control", id:"floatingInputDepartment", placeholder:"Finance" %>
    <%= form.label :description, for:"floatingInputDepartment"  %>
  </div>

    <div class="form-floating mb-3">
    <%= form.select :floor_id, options_for_select(Floor.order(:description).pluck(:description, :id)), {}, {class: "form-select "} %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<div class="row mb-3">
  <div class="col sm-8">
    <h1>Editing Department</h1>
  </div>
</div>
<%= render 'form', department: @department %>

app/views/departments/index.html.erb
<div class="row mb-3">
  <div class="col sm-8">
    <h5>Departments</h5>
  </div>
  <% if user_signed_in? %>
    <div class="col sm-8">
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= link_to 'New Department', new_department_path, class:"btn btn-primary text-white me-md-2 rounded-pill border border-light" %>
      </div>
    </div>
  <% end %>
</div>

<table class="table table-hover table-bordered">
  <thead class="table-secondary">
    <tr>
      <th>Description</th>
      <th>Floor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.description %></td>
        <td><%= department.floor.description %></td>
        <td><%= link_to 'Show', department, class: "text-primary" %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_department_path(department), class: "text-primary" %></td>
          <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' }, class:"text-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/departments/new.html.erb
<div class="row mb-3">
  <div class="col sm-8">
    <h1>New Department</h1>
  </div>
</div>
<%= render 'form', department: @department %>

app/views/departments/show.html.erb
<div class="card">
  <div class="card-header">
    <div class="row mb-3">
      <div class="col sm-8">
         <h1><%= @department.description %></h1>
      </div>
      <div class="col sm-8">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <% if user_signed_in? %>
            <%= link_to 'Edit', edit_department_path(@department),class:"btn btn-success text-white me-md-2" %>
          <% end %>
          <%= link_to 'Go Back', departments_path, class:"btn btn-outline-primary text-primary" %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-12">
        <div class="card">
          <div class="card-body mb-3">
            <p class="card-text mb-3"><strong>Floor: </strong><%= @department.floor.description %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>