config/routes.rb
Rails.application.routes.draw do
  resources :floors
  resources :departments
  devise_for :users
  resources :employees
  root 'home#index'

  get "export_contacts", to: "employees#export"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @employees = Employee.all
    @departments = Department.all
    @floors = Floor.all

    @todays_birthdays = Employee.todays_birthdays.sort
    @upcoming_birthdays = Employee.upcoming_birthdays.order('date_of_birth ASC')
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_dashboard.html.erb
<div class="container-fluid">
  <h3 class="mb-3">Dashboard</h3>
  <div class="row">
    <div class="col-lg-3 col-6">

      <div class="small-box bg-lightblue">
        <div class="inner">
          <h3><%= @floors.length%></h3>
          <p>Floors</p>
        </div>
        <div class="icon">
          <i class="fas fa-ellipsis-h"></i>
        </div>
        <%= link_to floors_path, class:"small-box-footer", "data-bs-toggle":"tooltip", "data-bs-placement":"top", "title":"See All Floors" do %>
            See All <i class="fas fa-arrow-circle-right"></i>
        <% end %>
      </div>
    </div>
    <div class="col-lg-3 col-6">
      <div class="small-box bg-success">
        <div class="inner">
          <h3><%= @departments.length %></h3>

          <p>Departments</p>
        </div>
        <div class="icon">
          <i class="fas fa-th"></i>
        </div>
        <%= link_to departments_path, class:"small-box-footer", "data-bs-toggle":"tooltip", "data-bs-placement":"top", "title":"See All Departments" do %>
            See All <i class="fas fa-arrow-circle-right"></i>
        <% end %>
      </div>
    </div>
    <div class="col-lg-3 col-6">
      <div class="small-box bg-warning">
        <div class="inner">
          <h3><%= @employees.length %></h3>

          <p>Employees</p>
        </div>
        <div class="icon">
          <i class="fas fa-user"></i>
        </div>
        <%= link_to employees_path, class:"small-box-footer", "data-bs-toggle":"tooltip", "data-bs-placement":"top", "title":"See All Employees" do %>
            See All <i class="fas fa-arrow-circle-right"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/_navbar.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <span class="nav-item d-none d-sm-inline-block">
      <%= link_to "Home", root_path, class:"nav-link" %>
    </li>
  </ul>

  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <a class="nav-link" data-widget="navbar-search" href="#" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Search">
        <i class="fas fa-search"></i>
      </a>
      <div class="navbar-search-block">
        <form class="form-inline">
          <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit" data-bs-toggle="tooltip" data-bs-placement="top" title="Submit Search">
                <i class="fas fa-search"></i>
              </button>
              <button class="btn btn-navbar" type="button" data-widget="navbar-search" data-bs-toggle="tooltip" data-bs-placement="top" title="Cancel">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <li class="nav-item">
      <a class="nav-link" data-widget="fullscreen" href="#" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Full Screen">
        <i class="fas fa-expand-arrows-alt"></i>
      </a>
    </li>
    <li class="nav-item ml-2">
      <div class="image">
        <% if current_user %>
          <%= image_tag (current_user.photo.variant(resize: "50x50!").processed), class:"img-circle elevation-2", alt:"User Avatar", "data-widget": "control-sidebar", "data-slide": "true" %>
        <% else %>
          <%= image_tag ("avatar.jpg"), size:"50", class:"img-circle elevation-2", alt:"User Avatar", "data-widget": "control-sidebar", "data-slide": "true" %>
        <% end %>
      </div>
      </a>
    </li>
  </ul>
</nav>

<aside class="control-sidebar control-sidebar-light" style="display: block;">
  <div class="p-3 control-sidebar-content">
    <div class="mb-4">
      <a class="d-block mr-1" style="text-decoration: none; color: gray;">
        <% if user_signed_in? %>
          Welcome
          <%= link_to current_user.email, edit_user_registration_path, style:"color: gray;" %>
        <% else %>
          Welcome!!
        <% end %>
      </a>
    </div>
    <hr class="mb-2">
    <div class="mb-1">
      <span class="mr-1" style="color: gray;>
        <% if user_signed_in? %>
          <%= link_to 'Logout',destroy_user_session_path, method: :delete, class:"nav-link", "data-bs-toggle":"tooltip", "data-bs-placement":"top", title:"Logout" %>
        <% else %>
          <%= link_to 'Sing In', new_user_session_path, class:"nav-link", "data-bs-toggle":"tooltip", "data-bs-placement":"top", title:"Sign In" %>
        <% end %>
      </span>
    </div>
  </div>
</aside>

app/views/home/_sidebar.html.erb
<aside class="main-sidebar sidebar-light-primary elevation-4" style="position: fixed">
  <a class="brand-link" style="text-decoration: none">
    <span class="brand-text font-weight-light" style="text-decoration: none">Contact List v1</span>
  </a>

  <div class="sidebar">
    <div class="form-inline">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div>

    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              General
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <%= link_to root_path, class:"nav-link" do %>
                <i class="far fa-circle nav-icon"></i>
                <p>Dashboard</p>
              <% end %>
            </li>
          </ul>
        </li>
        <li class="nav-item">
        <%= link_to departments_path, class:"nav-link" do %>
            <i class="nav-icon fas fa-th"></i>
            <p>
              Departments
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to floors_path, class:"nav-link" do %>
            <i class="nav-icon fas fa-ellipsis-h"></i>
            <p>
              Floors
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to employees_path, class:"nav-link" do %>
            <i class="nav-icon fas fa-user"></i>
            <p>
              Employees
            </p>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</aside>

app/views/home/_upcoming_birthdays.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3 col-sm-6 col-12">
      <div class="card">
        <div class="card-header ui-sortable-handle">
          <h3 class="card-title">Todays Birthdays</h3>
        </div>
          <div class="card-body">
            <% @todays_birthdays.each do |todays_birthday| %>
              <div class="row">
                <div class="col-md-3 col-sm-6 col-12">
                  <div class="info-box">
                    <div class="info-box-icon">
                      <div class="widget-user-image">
                        <%= image_tag todays_birthday.photo_thumbnail_upcoming_birthdays,
                          class:"img-circle elevation-2", alt:"User Avatar"
                        %>
                      </div>
                    </div>
                    <div class="info-box-content">
                      <span class="info-box-number"><%= todays_birthday.first_name %> <%= todays_birthday.last_name %></span>
                      <span class="info-box-text"><%= todays_birthday.date_of_birth %></span>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
      </div>
    </div>

    <div class="col-lg-9 col-sm-6 col-12">
      <div class="card">
        <div class="card-header ui-sortable-handle">
          <h3 class="card-title">Upcoming Birthdays</h3>
        </div>
        <div class="card-body">
          <div class="row">
          </div>
          <div class="row">
            <% @upcoming_birthdays.each do |upcoming| %>
              <div class="col-md-3">
                <div class="card card-widget widget-user">
                  <div class="widget-user-header bg-lightblue">
                    <h3 class="widget-user-username"><%= upcoming.first_name %> <%= upcoming.last_name %></h3>
                    <h5 class="widget-user-desc"><%= upcoming.title %></h5>
                  </div>
                  <div class="widget-user-image">
                    <%= image_tag upcoming.photo_thumbnail_upcoming_birthdays,
                      class:"img-circle elevation-2", alt:"User Avatar"
                    %>
                  </div>
                  <div class="card-footer">
                    <div class="row">
                      <div class="col-sm-12">
                        <div class="description-block">
                          <h5 class="description-header"><%= upcoming.date_of_birth %></h5>
                          <span class="description-text">Date of Birth</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render partial: 'dashboard' %>
<%= render partial: 'upcoming_birthdays' %>