config/routes.rb
Rails.application.routes.draw do
  resources :floors
  resources :departments
  devise_for :users
  resources :employees
  root 'home#index'

  get "export_contacts", to: "employees#export"
end

app/models/floor.rb
class Floor < ApplicationRecord
  has_many :departments
end

app/controllers/floors_controller.rb
class FloorsController < ApplicationController
  before_action :set_floor, only: %i[ show edit update destroy ]

  # GET /floors or /floors.json
  def index
    @floors = Floor.all
  end

  # GET /floors/1 or /floors/1.json
  def show
  end

  # GET /floors/new
  def new
    @floor = Floor.new
  end

  # GET /floors/1/edit
  def edit
  end

  # POST /floors or /floors.json
  def create
    @floor = Floor.new(floor_params)

    respond_to do |format|
      if @floor.save
        format.html { redirect_to floor_url(@floor), notice: "Floor was successfully created!" }
        format.json { render :show, status: :created, location: @floor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @floor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /floors/1 or /floors/1.json
  def update
    respond_to do |format|
      if @floor.update(floor_params)
        format.html { redirect_to floor_url(@floor), notice: "Floor was successfully updated!" }
        format.json { render :show, status: :ok, location: @floor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @floor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /floors/1 or /floors/1.json
  def destroy
    @floor.destroy

    respond_to do |format|
      format.html { redirect_to floors_url, notice: "Floor was successfully destroyed!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_floor
      @floor = Floor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def floor_params
      params.require(:floor).permit(:description)
    end
end

app/helpers/floors_helper.rb
module FloorsHelper
end

app/views/floors/_form.html.erb
<%= form_with(model: floor) do |form| %>
  <% if floor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(floor.errors.count, "error") %> prohibited this floor from being saved:</h2>

      <ul>
        <% floor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col sm-8 mb-3">
    <div class="actions">
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= form.submit class:"btn btn-success text-white me-md-2" %>
        <%= link_to 'Go Back', floors_path, class:"btn btn-outline-primary text-primary" %>
      </div>
    </div>
  </div>
  <div class="form-floating mb-3">
    <%= form.text_field :description, class:"form-control", id:"floatingInputFloor", placeholder:"Mezanine" %>
    <%= form.label :description, for:"floatingInputFloor" %>
  </div>
<% end %>

app/views/floors/edit.html.erb
<div class="row mb-3">
  <div class="col sm-8">
    <h1>Editing Floor</h1>
  </div>
</div>
<%= render 'form', floor: @floor %>

app/views/floors/index.html.erb
<div class="row mb-3">
  <div class="col sm-8">
    <h5>Floors</h5>
  </div>
  <% if user_signed_in? %>
    <div class="col sm-8">
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= link_to 'New Floor', new_floor_path, class:"btn btn-primary text-white me-md-2 rounded-pill border border-light" %>
      </div>
    </div>
  <% end %>
</div>

<table class="table table-hover table-bordered">
  <thead class="table-secondary">
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @floors.each do |floor| %>
      <tr>
        <td><%= floor.description %></td>
        <td><%= link_to 'Show', floor, class:"text-primary" %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_floor_path(floor), class:"text-primary" %></td>
          <td><%= link_to 'Destroy', floor, method: :delete, data: { confirm: 'Are you sure?' }, class:"text-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/floors/new.html.erb
<div class="row mb-3">
  <div class="col sm-8">
    <h1>New Floor</h1>
  </div>
</div>
<%= render 'form', floor: @floor %>

app/views/floors/show.html.erb
<div class="card">
  <div class="card-header">
    <div class="row mb-3">
      <div class="col sm-8">
         <h1>Floor</h1>
      </div>
      <div class="col sm-8">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <% if user_signed_in? %>
            <%= link_to 'Edit', edit_floor_path(@floor),class:"btn btn-success text-white me-md-2" %>
          <% end %>
          <%= link_to 'Go Back', floors_path, class:"btn btn-outline-primary text-primary" %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-12">
        <div class="card">
          <div class="card-body mb-3">
            <p class="card-text mb-3"><strong>Floor: </strong><%= @floor.description %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>